version: '3.8'

services:
  app:
    image: game-of-3
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
    external: true